### ISSUE TITLE
Implement "Selectable" Interface in AuditedCollection

### ISSUE THREAD

**Issue by JProffitt71** [sonata-project/EntityAuditBundle#269]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no

AuditedCollection does not implement Doctrine's Selectable interface, which means calls to `matching()`  will result in a method not found error. Since Doctrine's collections injected into entities implement this interface and they expect developers to make use of this method, AuditedCollection should too.

**Comment by DavidBadura** [comment]
Hey @JProffitt71 I have checked this. We can implement the `Selectable` interface, but you will have an another problem: 

If you use php7 then you can't set the return type to `ArrayCollection` because the `AuditedCollection` doesn't extend `ArrayCollection`. It implements `Collection` (and then `Selectable`). This trouble do you have not only with AuditedCollection. `PersistentCollection` doesn't extend `ArrayCollection` too.

With other words: you can set the return type to `Collection` or `Selectable` without exceptions. To be strict you *need* to check if the returned collection implements the `Selectable` interface.

**Comment by DavidBadura** [comment]
ref: https://github.com/knpuniversity/php7/issues/4

**Comment by JProffitt71** [comment]
To clarify, I consider this a bug because it throws errors even when you follow best practices:

```
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Selectable;
use Doctrine\Common\Collections\Criteria;

class MyEntity {
    /**
     * @var Selectable
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\MySubEntity", mappedBy="parentEntity")
     */
    protected $subEntities;

    public function __construct() {
        $this->subEntities = new ArrayCollection();
    }

    /**
     * @return Collection
     */
    public function getSubEntities()
    {
        return $this->subEntities->matching(
            Criteria::create()
                ->orderBy(array("someProperty" => Criteria::ASC))
        );
    }

}
```

Inside the entity it's expected that Doctrine injects a Selectable object (both ArrayCollection and PersistentCollection implement Selectable). If both "MyEntity" and "MySubEntity" are audited and you load a revision of MyEntity, then you will get an error as soon as you access "getSubEntities" on that revision.

```
$myEntity = $myEntityRepo->find($someId);
$myEntity->getSubEntities(); // Works

$myEntityAudit = $auditReader->find(
    'AppBundel\Entity\MyEntity',
    $someId,
    $someRev
);
$myEntityAudit->getSubEntities(); // Throws error
```

**Comment by SumonMSelim** [comment]
I am using Audit feature in Sonata Admin and getting this error that `matching()` method not exists in `AuditedCollection`. Any update or progress to fix this yet?
