### ISSUE TITLE
All fields on the revision table are marked as not null.

### ISSUE THREAD

**Issue by c-butcher** [sonata-project/EntityAuditBundle#318]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Used Version     | 1.0.8

The revision table that is created during the schema generation is marking all of the fields as "NOT NULL", even though a lot of them are nullable. This is causing integrity constraint violations when a revision is saved.

**Comment by montaniasystemab** [comment]
It seems like this issue is introduced with doctrine/dbal v2.7, for a quick workaround you might solve this issue by locking doctrine/dbal to version v2.6 in your composer file:

`"doctrine/dbal": "v2.6.*"`

**Comment by c-butcher** [comment]
Thanks, I'll try that out and see what happens. While my solution worked for my specific case, I just realized that `'notnull' => false` is the same as `'null' => true`. Having double negatives in the code is -really- confusing.

So does this mean that the EntityAuditBundle is not compatible with Doctrine/DBAL > 2.6 and is there a plan to make it compatible?

**Comment by tolry** [comment]
@c-butcher as we have no real active maintainer of this package, it's sure to say, that no tests against dbal 2.7 were done :smile: 2.6->2.7 should in theory have no BC breaks, ... therefore version restrictions in EntityAuditBundle allow `<3.0`

If changes can be made to allow usage with any 2.x version, I am happy to merge those.

For the double negatives: I agree, quite confusing - I guess the reason for this in doctrine was to make  not-nullable the default, since nullable collumns always make trouble in edge cases :grin:

**Comment by axzx** [comment]
There are more problems

`./bin/console d:s:u --dump-sql`:

```
ALTER TABLE app_state_audit ALTER pa_id TYPE VARCHAR(255);
ALTER TABLE app_tag_audit ALTER use_counter DROP DEFAULT;
ALTER TABLE user_company_audit ALTER minimum_order_value TYPE NUMERIC(10, 0);
```

my db schma:
```
CREATE TABLE app_state
(  
  pa_id character varying(3) DEFAULT NULL::character varying
)

CREATE TABLE app_tag
(
  use_counter integer NOT NULL DEFAULT 0,
)

CREATE TABLE user_company
(
  minimum_order_value numeric(9,2) DEFAULT NULL::numeric,
)
```

**Comment by phansys** [comment]
@c-butcher, could you please confirm if #320 fixes the issue?
Thank you.
