### ISSUE TITLE
What happened to this project? It is transfer to `sonata-project`.

### ISSUE THREAD

**Issue by videni** [sonata-project/EntityAuditBundle#343]
almost three years old, still get lots of attention, 1 615 861 dowloads in packgist,  but no PR are accepted.

**Comment by videni** [comment]
it seems this project is actively used by  [martin-georgiev/EntityAuditBundle](https://github.com/martin-georgiev/EntityAuditBundle).

**Comment by maguramarkian** [comment]
@tolry   can you please  answer or set this project as abandoned

**Comment by tolry** [comment]
Hi, haven't been in charge for quite some time and haven't even been using the bundle anywhere, so I can't say anything about this. General discussion about project's status was here #3605 

Maybe @sewah or @hnadler can give a little more insight here?

**Comment by VincentLanglet** [comment]
What about adding new maintainer ? 
@phansys proposed himself https://github.com/simplethings/EntityAuditBundle/issues/203#issuecomment-380681587

**Comment by wbloszyk** [comment]
Since February 2021 this project will be maintain and contribute by sonata-project.

It was transfered becouse:
- there was no active  development going on (on `simplethings/entity-audit-bundle`)
- ~90% of the downloads for this bundle come from sonata users
-  @beberlei - who initially wrote this bundle - suggested for sonata to maybe pick up the bundle - https://github.com/sonata-project/EntityAuditBundle/pull/346#issuecomment-767374968

To keep backward compatibility we do not change namespaces.
